unique_shuffled_list = [

    'Remember that time is money. - Benjamin Franklin',
    'The way to wealth is as plain as the way to market. It depends chiefly on two words, industry and frugality. - Benjamin Franklin',
    'I will tell you the secret to getting rich on Wall Street. You try to be greedy when others are fearful. And you try to be fearful when others are greedy. - Warren Buffett',
    "Rich people believe 'I create my life'. Poor people believe 'Life happens to me'. - T. Harv Eker",
    'Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble. - Warren Buffet',
    "It's not your salary that makes you rich, it's your spending habits. - Charles A. Jaffe",
    'The greatest reward in becoming a millionaire is not the amount of money that you earn. It is the kind of person that you have to become to become a millionaire. - Jim Rohn',
    'An investment in knowledge pays the best interest. - Benjamin Franklin',
    "Success is not just making money. Success is happiness. Success is fulfillment; it's the ability to give. - Adam Neumann",
    "Don't tell me what you value, show me your budget, and I'll tell you what you value. - Joe Biden",
    "The best investment is in the tools of one's own trade. - Benjamin Franklin",
    'A good financial plan is a road map that shows us exactly how the choices we make today will affect our future. - Alexa Von Tobel',
    'The safe way to double your money is to fold it over once and put it in your pocket. - Kin Hubbard',
    'If you don’t find a way to make money while you sleep, you will work until you die. - Warren Buffett',
    "It's not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for. - Robert Kiyosaki",
    'If you want to be successful, find out what the price is and then pay it. - Scott Adam',
    'Don’t tell me where your priorities are. Show me where you spend your money and I’ll tell you what they are. - James W. Frick',
    'Know what you own, and know why you own it. - Peter Lynch',
    'There are no secrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell',
    'Money is good for nothing unless you know the value of it by experience. - P.T Barnum',
    "You can't get rich in politics unless you're a crook. - Harry Truman",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    'I will tell you the secret to getting rich on Wall Street. You try to be greedy when others are fearful. And you try to be fearful when others are greedy. - Warren Buffet',
    'Don’t aim for success if you want it; just do what you love and believe in, and it will come naturally. - David Frost',
    'The best way to predict your future is to create it. - Peter Drucker',
    'Success is not to be pursued; it is to be attracted by the person you become. - Jim Rohn',
    "Money is multiplied in practical value depending on the number of W's you control in your life: what you do, when you do it, where you do it, and with whom you do it. - Timothy Ferriss",
    "Every day is a bank account, and time is our currency. No one is rich, no one is poor, we've got 24 hours each. - Christopher Rice",
    'The key to success is action, and the essential in action is perseverance. - Sun Yat-sen',
    "Finance is not merely about making money. It's about achieving our deep goals and protecting the fruits of our labor. It's about stewardship and, therefore, about achieving the good society. - Robert J. Shiller",
    'Do not save what is left after spending, but spend what is left after saving. - Warren Buffett',
    "Don't think money does everything or you are going to end up doing everything for money. - Voltaire",
    'We make a living by what we get, but we make a life by what we give. - Winston Churchill',
    'He who buys what he does not need steals from himself. - Swedish Proverb',
    'A budget is telling your money where to go instead of wondering where it went. - John C. Maxwell',
    'I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. - Martha Stewart',
    'Money and women are the most sought after and the least known about of any two things we have. - Will Rogers',
    'Invest in yourself. Your career is the engine of your wealth. - Paul Clitheroe',
    'Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble. - Warren Buffett',
    'Money, if it does not bring you happiness, will at least help you be miserable in comfort. - Helen Gurley Brown',
    "Success does not lie in 'Results' but in 'Efforts'. 'Being' the best is not so important, 'Doing' the best is all that matters. - Unknown",
    'Money often costs too much. - Ralph Waldo Emerson',
    'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi',
    'I made my money the old-fashioned way. I was very nice to a wealthy relative right before he died. - Malcolm Forbes',
    'Wealth consists not in having great possessions, but in having few wants. - Epictetus',
    'The best way to predict the future is to create it. - Peter Drucker',
    'Time is more valuable than money. You can get more money, but you cannot get more time. - Jim Rohn',
    'The ladder of success is never crowded at the top. - Napoleon Hill',
    'Action is the foundational key to all success. - Pablo Picasso',
    "Too many people spend money they haven't earned, to buy things they don't want, to impress people they don't like. - Will Rogers",
    'The best thing money can buy is financial freedom. - Rob Berger',
    'What seems to us as bitter trials are often blessings in disguise. - Oscar Wilde',
    'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer',

    'Don’t think money does everything or you are going to end up doing everything for money. - Voltaire',
    "You can be young without money, but you can't be old without it. - Tennessee Williams",
    "The goal isn't more money. The goal is living life on your terms. - Chris Brogan",
    'You must gain control over your money or the lack of it will forever control you. - Dave Ramsey',
    'The road to success and the road to failure are almost exactly the same. - Colin R. Davis',
    'Never stand begging for that which you have the power to earn. - Miguel de Cervantes',
    'Opportunity is missed by most people because it is dressed in overalls and looks like work. - Thomas Edison',
    'The way to become rich is to put all your eggs in one basket and then watch that basket. - Andrew Carnegie',
    'Money, like emotions, is something you must control to keep your life on the right track. - Natasha Munson',
    'Failure is success if we learn from it. - Malcolm Forbes',
    'I feel that luck is preparation meeting opportunity. - Oprah Winfrey',
    "Many folks think they aren't good at earning money, when what they don't know is how to use it. - Frank A. Clark",
    'Strive not to be a success, but rather to be of value. - Albert Einstein',
    'It’s good to have money and the things that money can buy, but it’s good, too, to check up once in a while and make sure that you haven’t lost the things that money can’t buy. - George Lorimer',
    'If you wish to succeed in life, make perseverance your bosom friend, experience your wise counselor, caution your elder brother, and hope your guardian genius. - Joseph Addison',
    "You reach a point where you don't work for money. - Walt Disney",
    'Success comes from knowing that you did your best to become the best that you are capable of becoming. - John Wooden',
    'Don’t work for money; make it work for you. - Robert Kiyosaki',
    'The secret of success is making your vocation your vacation. - Mark Twain',
    "It is not wealth one asks for, but just enough to preserve one's dignity, to work unhampered, to be generous, frank and independent. - W. Somerset Maugham",
    "It's not the employer who pays the wages. Employers only handle the money. It's the customer who pays the wages. - Henry Ford",
    'Money is a guarantee that we may have what we want in the future. Though we need nothing at the moment it insures the possibility of satisfying a new desire when it arises. - Aristotle',
    'The quickest way to double your money is to fold it over and put it back in your pocket. - Will Rogers',
    'The road to success is dotted with many tempting parking spaces. - Will Rogers',
    'Formal education will make you a living; self-education will make you a fortune. - Jim Rohn',
    'Money grows on the tree of persistence. - Japanese Proverb',
    'The more you learn, the more you earn. - Warren Buffett',
    'The most important investment you can make is in yourself. - Warren Buffett',
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
    'The key to success is failure. - Michael Jordan',
    'In order to succeed, we must first believe that we can. - Nikos Kazantzakis',
    'A wise person should have money in their head, but not in their heart. - Jonathan Swift',
    "To get rich, you have to be making money while you're asleep. - David Bailey",
    'What we really want to do is what we are really meant to do. When we do what we are meant to do, money comes to us, doors open for us, we feel useful, and the work we do feels like play to us. - Julia Cameron',
    'Wealth is not his that has it, but his that enjoys it. - Benjamin Franklin',
    'Success comes to those who dedicate everything to their passion in life. To be successful, it is also very important to be humble and never let fame or money travel to your head. - A. R. Rahman',
    "Don't aim for success if you want it; just do what you love and believe in, and it will come naturally. - David Frost",
    'Wealth flows from energy and ideas. - William Feather',
    'The stock market is a device for transferring money from the impatient to the patient. - Warren Buffett',
    'The art is not in making money, but in keeping it. - Proverb',
    'Money won’t create success, the freedom to make it will. - Nelson Mandela',
    'The key to making money is to stay invested. - Suze Orman',
    'Success isn’t just about making money. It’s about making a difference. - Anonymous',
    "Money can't buy friends, but you can get a better class of enemy. - Spike Milligan",
    'The successful man is the one who finds out what is the matter with his business before his competitors do. - Roy L. Smith',
    "It's not about how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for. - Robert Kiyosaki",
    'It’s not your salary that makes you rich, it’s your spending habits. - Charles A. Jaffe',
    'The path to success is to take massive, determined actions. - Tony Robbins',
    'Saving is a great habit but without investing and tracking, it just sleeps - Manoj Arora',
    "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
    'A big part of financial freedom is having your heart and mind free from worry about the what-ifs of life. - Suze Orman',
    'The best way to become a billionaire is to help a billion people. - Peter Diamandis',
    'Many people take no care of their money till they come nearly to the end of it, and others do just the same with their time. - Johann Wolfgang von Goethe',
    'Successful people are simply those with successful habits. - Brian Tracy',
    "Success is simple. Do what's right, the right way, at the right time. - Arnold H. Glasow",
    'The only place where success comes before work is in the dictionary. - Vidal Sassoon',
    "Success is not a destination, but the road that you're on. Being successful means that you're working hard and walking your walk every day. - Marlon Wayans",
    "You've got to tell your money what to do or it will leave. - Dave Ramsey",
    'If you live for having it all, what you have is never enough. - Vicki Robin',
    'Money can’t buy happiness, but it will certainly get you a better class of memories. - Ronald Reagan',
    "Money won't create success, the freedom to make it will. - Nelson Mandela",
    "Success is not just about making money. It's about making a difference. - Unknown",
    'Success means having the courage, the determination, and the will to become the person you believe you were meant to be. - George Sheehan',
    'Try not to become a man of success. Rather become a man of value. - Albert Einstein',
    'To be successful, you have to have your heart in your business, and your business in your heart. - Sr. Thomas Watson',
    'I never dreamed about success, I worked for it. - Estee Lauder',
    'Always bear in mind that your own resolution to succeed is more important than any other. - Abraham Lincoln',
    "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time. - Steve Jobs",
    "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier, wish you were better. - Jim Rohn",
    'Success is doing what you want to do, when you want, where you want, with whom you want, as much as you want. - Tony Robbins',
    'The secret to success is to know something nobody else knows. - Aristotle Onassis',
    "You get recessions, you have stock market declines. If you don't understand that's going to happen, then you're not ready, you won't do well in the markets. - Peter Lynch",
    'The secret of your success is determined by your daily agenda. - John C. Maxwell',
    'Do not be embarrassed by your failures, learn from them and start again. - Richard Branson',
    'Money is not the most important thing in the world. Love is. Fortunately, I love money. - Jackie Mason',
    'In the business world, the rearview mirror is always clearer than the windshield. - Warren Buffett',
    'The art of living easily as to money is to pitch your scale of living one degree below your means. - Sir Henry Taylor',
    'The only limit to your impact is your imagination and commitment. - Tony Robbins',
    'If we command our wealth, we shall be rich and free. If our wealth commands us, we are poor indeed. - Edmund Burke',
    'To understand the heart and mind of a person, look not at what he has already achieved, but at what he aspires to. - Kahlil Gibran',
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
    'Frugality includes all the other virtues. - Cicero',
    'The secret of success is to do the common things uncommonly well. - John D. Rockefeller Jr.',
    "Opportunities don't happen. You create them. - Chris Grosser",
    'Your wealth can only grow to the extent that you do! - T. Harv Eker',
    'Wealth is the ability to truly experience life. - Henry David Thoreau',
    'Success is having to worry about every damn thing in the world, except money. - Johnny Cash',
    'Money is a servant, not a master. Let it serve you, not rule you. - Shiv Khera',
    'To acquire money requires valor, to keep money requires prudence, and to spend money well is an art. - Berthold Auerbach',
    'If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success. - John D. Rockefeller',
    'Financial freedom is available to those who learn about it and work for it. - Robert Kiyosaki',
    'I attribute my success to this: I never gave or took any excuse. - Florence Nightingale',
    'Every dollar you invest in your personal development adds 30 to your bottom line. - Brian Tracy',
    'Wealth is largely the result of habit. - John Jacob Astor',
    "The person who doesn't know where his next dollar is coming from usually doesn't know where his last dollar went. - Unknown",
    'Too many people spend money they earned..to buy things they don’t want..to impress people that they don’t like. - Will Rogers',
    "The only way to permanently change the temperature in the room is to reset the thermostat. In the same way, the only way to change your level of financial success 'permanently' is to reset your financial thermostat. But it is your choice whether you choose to change. - T. Harv Eker",
    'Success is falling nine times and getting up ten. - Jon Bon Jovi',
    'Success is sweet: the sweeter if long delayed and attained through manifold struggles and defeats. - Amos Bronson Alcott',
    'A nickel ain’t worth a dime anymore. - Yogi Berra',
    "It's good to have money and the things that money can buy, but it's good, too, to check up once in a while and make sure that you haven't lost the things that money can't buy. - George Lorimer",
    'You can only become truly accomplished at something you love. Don’t make money your goal. Instead, pursue the things you love doing, and then do them so well that people can’t take their eyes off you. - Maya Angelou',
    'Before you speak, listen. Before you write, think. Before you spend, earn. Before you invest, investigate. Before you criticize, wait. Before you pray, forgive. Before you quit, try. Before you retire, save. Before you die, give. - William A. Ward',
    'Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones. - Benjamin Franklin',
    'Not he who has much is rich, but he who gives much. - Erich Fromm',
    "Money can't buy happiness, but it's a lot more comfortable to cry in a Mercedes than on a bicycle. - John Lennon",
    'Empty pockets never held anyone back. Only empty heads and empty hearts can do that. - Norman Vincent Peale',
    'It’s not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for. - Robert Kiyosaki',
    'To accomplish great things, we must not only act, but also dream; not only plan, but also believe. - Anatole France',
    'Money is not the only answer, but it makes a difference. - Barack Obama',
    "Money can't buy happiness, but it can make you awfully comfortable while you're being miserable. - Clare Boothe Luce",
    'Beware of small expenses. A small leak will sink a great ship. - Benjamin Franklin',
    'Believing in yourself is the first secret to success. - Unknown',
    "Rich people believe 'I create my life.' Poor people believe 'Life happens to me.' - T. Harv Eker",
    'People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins',
    "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit. - Conrad Hilton",
    "Money can't buy happiness, but it will certainly get you a better class of memories. - Ronald Reagan",
    'Patience, persistence and perspiration make an unbeatable combination for success. - Napoleon Hill',
    'Time is more value than money. You can get more money, but you cannot get more time. - Jim Rohn',
    "It's how you deal with failure that determines how you achieve success. - David Feherty",
    'Money is not everything. Make sure you earn a lot before speaking such nonsense. - Warren Buffett',
    "Don't let money run your life, let money help you run your life better. - John Rampton",
    "Don't wait. The time will never be just right. - Napoleon Hill",
    "Don't be distracted by criticism. Remember--the only taste of success some people get is to take a bite out of you. - Zig Ziglar",
    'Success is not counted by how high you have climbed but by how many people you brought with you. - Wil Rose',
    'Success is not a good teacher, failure makes you humble. - Shah Rukh Khan',
    'The cost of a thing is the amount of what I call life which is required to be exchanged for it, immediately or in the long run. - Henry David Thoreau',
    'When it is a question of money, everybody is of the same religion. - Voltaire',
    'The key to success is to start before you are ready. - Marie Forleo',
    "Every time you borrow money, you're robbing your future self. - Nathan W. Morris",
    'You become financially free when your passive income exceeds your expenses. - T. Harv Eker',
    'The real secret of success is enthusiasm. - Walter Chrysler',
    'Success is the sum of small efforts, repeated day in and day out. - Robert Collier',
    'The successful warrior is the average man, with laser-like focus. - Bruce Lee',
    'Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort. - Franklin D. Roosevelt',
    'Your success and happiness lies in you. Resolve to keep happy, and your joy and you shall form an invincible host against difficulties. - Helen Keller',
    'Success is not in never failing, but rising every time you fall! - Jonathan Taylor Thomas',
    'The real measure of your wealth is how much you’d be worth if you lost all your money. - Unknown',
    'Investing money is the process of committing resources in a strategic way to accomplish a specific objective. - Alan Gotthardt',
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    'He who loses money, loses much; He who loses a friend, loses much more; He who loses faith, loses all. - Eleanor Roosevelt',
    'You always pass failure on the way to success. - Mickey Rooney',
    'The key to success is to focus on goals, not obstacles. - Unknown',
    'The secret of getting ahead is getting started. - Mark Twain',
    'Never spend your money before you have it. - Thomas Jefferson',
    'The hardest thing in the world to understand is the income tax. - Albert Einstein',
    'Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau',
    'Never spend your money before you have earned it. - Thomas Jefferson',
    'The best revenge is massive success. - Frank Sinatra',
    'Wealth is the ability to fully experience life. - Henry David Thoreau',
    'If you really look closely, most overnight successes took a long time. - Steve Jobs',
    "A budget tells us what we can't afford, but it doesn't keep us from buying it. - William Feather",
    "Wealth is not about having a lot of money; it's about having a lot of options. - Chris Rock",
    'If you wish to get rich, save what you get. A fool can earn money; but it takes a wise man to save and dispose of it to his own advantage. - Brigham Young',
    'The best thing money can buy is financial freedom. - Unknown',
    'The quickest way to double your money is to fold it in half and put it in your back pocket. - Will Rogers',
    'I find that the harder I work, the more luck I seem to have. - Thomas Jefferson',
    'Investing is not nearly as difficult as it looks. Successful investing involves doing a few things right and avoiding serious mistakes. - John C. Bogle',
    'Try to save something while your salary is small; it’s impossible to save after you begin to earn more. - Jack Benny',
    'Always remember that striving and struggle precede success, even in the dictionary. - Sarah Ban Breathnach',
    'I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite. - G. K. Chesterton',
    "Don't tell me where your priorities are. Show me where you spend your money, and I'll tell you what they are. - James W. Frick",
    "The four most dangerous words in investing are: 'this time it's different.' - Sir John Templeton",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
    'I don’t pay good wages because I have a lot of money; I have a lot of money because I pay good wages. - Robert Bosch',
    'The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey',
    'You can be young without money, but you can’t be old without it. - Tennessee Williams',
    'Success is getting what you want. Happiness is wanting what you get. - Dale Carnegie',
    'The individual investor should act consistently as an investor and not as a speculator. - Benjamin Graham',
    'The man who damns money has obtained it dishonorably; the man who respects it has earned it. - Ayn Rand',
    'The best thing money can buy is financial freedom. - Anonymous',
    'A strong, positive self-image is the best possible preparation for success. - Joyce Brothers']