quotes = [

    "Dont aim for success if you want it; just do what you love and believe in, and it will come naturally. - David Frost",
    "Dont be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Dont tell me what you value, show me your budget, and Ill tell you what you value. - Joe Biden",
    "Dont think money does everything or you are going to end up doing everything for money. - Voltaire",
    "Finance is not merely about making money. Its about achieving our deep goals and protecting the fruits of our labor. Its about stewardship and, therefore, about achieving the good society. - Robert J. Shiller",
    "It is not wealth one asks for, but just enough to preserve ones dignity, to work unhampered, to be generous, frank and independent. - W. Somerset Maugham",
    "Its not about how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for. - Robert Kiyosaki",
    "Its not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for. - Robert Kiyosaki",
    "Its not the employer who pays the wages. Employers only handle the money. Its the customer who pays the wages. - Henry Ford",
    "Its not your salary that makes you rich, its your spending habits. - Charles A. Jaffe",
    "Many folks think they arent good at earning money, when what they dont know is how to use it. - Frank A. Clark",
    "Money cant buy friends, but you can get a better class of enemy. - Spike Milligan",
    "Money is multiplied in practical value depending on the number of Ws you control in your life: what you do, when you do it, where you do it, and with whom you do it. - Timothy Ferriss",
    "Rich people believe I create my life. Poor people believe Life happens to me. - T. Harv Eker",
    "Success does not lie in Results but in Efforts. Being the best is not so important, Doing the best is all that matters. - Unknown",
    "Success is not a destination, but the road that youre on. Being successful means that youre working hard and walking your walk every day. - Marlon Wayans",
    "Success is not just making money. Success is happiness. Success is fulfillment; its the ability to give. - Adam Neumann",
    "Success is not the absence of failure; its the persistence through failure. - Aisha Tyler",
    "Success is simple. Do whats right, the right way, at the right time. - Arnold H. Glasow",
    "The best investment is in the tools of ones own trade. - Benjamin Franklin",
    "The goal isnt more money. The goal is living life on your terms. - Chris Brogan",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you cant achieve it. - Jordan Belfort",
    "To get rich, you have to be making money while youre asleep. - David Bailey",
    "Too many people spend money they havent earned, to buy things they dont want, to impress people they dont like. - Will Rogers",
    "You can be young without money, but you cant be old without it. - Tennessee Williams",
    "You cant get rich in politics unless youre a crook. - Harry Truman",
    "You reach a point where you dont work for money. - Walt Disney",
    "Youve got to tell your money what to do or it will leave. - Dave Ramsey",
    "A big part of financial freedom is having your heart and mind free from worry about the what-ifs of life. - Suze Orman",
    "A budget is telling your money where to go instead of wondering where it went. - John C. Maxwell",
    "A good financial plan is a road map that shows us exactly how the choices we make today will affect our future. - Alexa Von Tobel",
    "A wise person should have money in their head, but not in their heart. - Jonathan Swift",
    "Action is the foundational key to all success. - Pablo Picasso",
    "An investment in knowledge pays the best interest. - Benjamin Franklin",
    "Do not save what is left after spending, but spend what is left after saving. - Warren Buffett",
    "Don’t aim for success if you want it; just do what you love and believe in, and it will come naturally. - David Frost",
    "Don’t tell me where your priorities are. Show me where you spend your money and I’ll tell you what they are. - James W. Frick",
    "Don’t think money does everything or you are going to end up doing everything for money. - Voltaire",
    "Don’t work for money; make it work for you. - Robert Kiyosaki",
    "Failure is success if we learn from it. - Malcolm Forbes",
    "Formal education will make you a living; self-education will make you a fortune. - Jim Rohn",
    "He who buys what he does not need steals from himself. - Swedish Proverb",
    "I will tell you the secret to getting rich on Wall Street. You try to be greedy when others are fearful. And you try to be fearful when others are greedy. - Warren Buffet",
    "I will tell you the secret to getting rich on Wall Street. You try to be greedy when others are fearful. And you try to be fearful when others are greedy. - Warren Buffett",
    "If you don’t find a way to make money while you sleep, you will work until you die. - Warren Buffett",
    "If you want to be successful, find out what the price is and then pay it. - Scott Adam",
    "If you wish to succeed in life, make perseverance your bosom friend, experience your wise counselor, caution your elder brother, and hope your guardian genius. - Joseph Addison",
    "In order to succeed, we must first believe that we can. - Nikos Kazantzakis",
    "In order to succeed, your desire for success should be greater than your fear of failure. - Bill Cosby",
    "Invest in yourself. Your career is the engine of your wealth. - Paul Clitheroe",
    "It’s good to have money and the things that money can buy, but it’s good, too, to check up once in a while and make sure that you haven’t lost the things that money can’t buy. - George Lorimer",
    "It’s not your salary that makes you rich, it’s your spending habits. - Charles A. Jaffe",
    "Know what you own, and know why you own it. - Peter Lynch",
    "Many people take no care of their money till they come nearly to the end of it, and others do just the same with their time. - Johann Wolfgang von Goethe",
    "Money grows on the tree of persistence. - Japanese Proverb",
    "Money is a guarantee that we may have what we want in the future. Though we need nothing at the moment it insures the possibility of satisfying a new desire when it arises. - Aristotle",
    "Money is good for nothing unless you know the value of it by experience. - P.T Barnum",
    "Money often costs too much. - Ralph Waldo Emerson",
    "Money won’t create success, the freedom to make it will. - Nelson Mandela",
    "Money, if it does not bring you happiness, will at least help you be miserable in comfort. - Helen Gurley Brown",
    "Money, like emotions, is something you must control to keep your life on the right track. - Natasha Munson",
    "Never stand begging for that which you have the power to earn. - Miguel de Cervantes",
    "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble. - Warren Buffet",
    "Opportunity is missed by most people because it is dressed in overalls and looks like work. - Thomas Edison",
    "Remember that time is money. - Benjamin Franklin",
    "Saving is a great habit but without investing and tracking, it just sleeps - Manoj Arora",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Success comes from knowing that you did your best to become the best that you are capable of becoming. - John Wooden",
    "Success comes to those who dedicate everything to their passion in life. To be successful, it is also very important to be humble and never let fame or money travel to your head. - A. R. Rahman",
    "Success is not to be pursued; it is to be attracted by the person you become. - Jim Rohn",
    "Success isn’t just about making money. It’s about making a difference. - Anonymous",
    "Successful people are simply those with successful habits. - Brian Tracy",
    "The art is not in making money, but in keeping it. - Proverb",
    "The best thing money can buy is financial freedom. - Rob Berger",
    "The best way to become a billionaire is to help a billion people. - Peter Diamandis",
    "The best way to predict your future is to create it. - Peter Drucker",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
    "The greatest reward in becoming a millionaire is not the amount of money that you earn. It is the kind of person that you have to become to become a millionaire. - Jim Rohn",
    "The key to making money is to stay invested. - Suze Orman",
    "The key to success is action, and the essential in action is perseverance. - Sun Yat-sen",
    "The key to success is failure. - Michael Jordan",
    "The ladder of success is never crowded at the top. - Napoleon Hill",
    "The more you learn, the more you earn. - Warren Buffett",
    "The most important investment you can make is in yourself. - Warren Buffett",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "The path to success is to take massive, determined actions. - Tony Robbins",
    "The quickest way to double your money is to fold it over and put it back in your pocket. - Will Rogers",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "The road to success is dotted with many tempting parking spaces. - Will Rogers",
    "The safe way to double your money is to fold it over once and put it in your pocket. - Kin Hubbard",
    "The secret of success is making your vocation your vacation. - Mark Twain",
    "The stock market is a device for transferring money from the impatient to the patient. - Warren Buffett",
    "The successful man is the one who finds out what is the matter with his business before his competitors do. - Roy L. Smith",
    "The way to wealth is as plain as the way to market. It depends chiefly on two words, industry and frugality. - Benjamin Franklin",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell",
    "Time is more valuable than money. You can get more money, but you cannot get more time. - Jim Rohn",
    "We make a living by what we get, but we make a life by what we give. - Winston Churchill",
    "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
    "Wealth flows from energy and ideas. - William Feather",
    "Wealth is not his that has it, but his that enjoys it. - Benjamin Franklin",
    "What we really want to do is what we are really meant to do. When we do what we are meant to do, money comes to us, doors open for us, we feel useful, and the work we do feels like play to us. - Julia Cameron",
    "You must gain control over your money or the lack of it will forever control you. - Dave Ramsey",
    "A budget is telling your money where to go instead of wondering where it went. - John C. Maxwell",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "A lack of money is never a problem; a lack of an idea is a problem. - Ken Hakuta",
    "A penny saved is a penny earned. - Benjamin Franklin",
    "A small leak can sink a great ship. - Benjamin Franklin",
    "A wise person should have money in their head, but not in their heart. - Jonathan Swift",
    "An investment in knowledge pays the best interest. - Benjamin Franklin",
    "Beware of little expenses; a small leak will sink a great ship. - Benjamin Franklin",
    "Buy when everyone else is selling and hold until everyone else is buying. Thats not just a catchy slogan. Its the very essence of successful investing. - J. Paul Getty",
    "Do not save what is left after spending, but spend what is left after saving. - Warren Buffett",
    "Dont count the days, make the days count. - Muhammad Ali",
    "Dont save what is left after spending; spend what is left after saving. - Warren Buffett",
    "Dont tell me where your priorities are. Show me where you spend your money, and Ill tell you what they are. - James W. Frick",
    "Dont watch the clock; do what it does. Keep going. - Sam Levenson",
    "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
    "Financial freedom is available to those who learn about it and work for it. - Robert Kiyosaki",
    "Financial freedom is less about money and more about living life on your terms. - Grant Sabatier",
    "Financial peace isnt the acquisition of stuff. Its learning to live on less than you make, so you can give money back and have money to invest. - Dave Ramsey",
    "Formal education will make you a living; self-education will make you a fortune. - Jim Rohn",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "I have not failed. Ive just found 10,000 ways that wont work. - Thomas Edison",
    "If you aim at nothing, you will hit it every time. - Zig Ziglar",
    "If you dont find a way to make money while you sleep, you will work until you die. - Warren Buffett",
    "If you want to reap financial blessings, you have to sow financially. - Joel Osteen",
    "In the world of money and investing, you need to learn to control your emotions. - Warren Buffett",
    "Invest in yourself, and your wealth will grow. - Unknown",
    "Investing is an action that should only be taken after careful consideration. - Unknown",
    "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas. - Paul Samuelson",
    "Its not about being the best. Its about being better than you were yesterday. - Unknown",
    "Its not about having a lot of money. Its about knowing how to manage what you have. - Unknown",
    "Its not about how much money you make, but how much money you keep. - Robert Kiyosaki",
    "Its not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. - Charles Darwin",
    "Its not what you earn but what you save. - Proverb",
    "Its not your salary that makes you rich, its your spending habits. - Charles A. Jaffe",
    "Know what you own, and know why you own it. - Peter Lynch",
    "Live within your means, even if you have to borrow money to do so. - Josh Billings",
    "Money cant buy happiness, but it can buy you the kind of misery you prefer. - Unknown",
    "Money grows on the tree of patience. - Japanese Proverb",
    "Money is a terrible master but an excellent servant. - P.T. Barnum",
    "Money is usually attracted, not pursued. - Jim Rohn",
    "Never spend your money before you have earned it. - Thomas Jefferson",
    "Never test the depth of the river with both feet. - African Proverb",
    "Opportunities dont happen. You create them. - Chris Grosser",
    "Rich people plan for three generations; poor people plan for Saturday night. - Gloria Steinem",
    "Savings, remember, is the prerequisite of investment. - Campbell McConnell",
    "Someones sitting in the shade today because someone planted a tree a long time ago. - Warren Buffett",
    "Success is a lousy teacher. It seduces smart people into thinking they cant lose. - Bill Gates",
    "Success is falling down seven times and getting up eight. - Japanese Proverb",
    "Success is getting what you want, happiness is wanting what you get. - Dale Carnegie",
    "Success is going from failure to failure without losing your enthusiasm. - Winston Churchill",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "Success is not a destination; its a journey. - Zig Ziglar",
    "Success is not about money, its about making a difference. - Unknown",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not for the chosen few; its for the few who choose it. - Unknown",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Success is not just about making money. Its about making a difference. - Unknown",
    "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds. - Orison Swett Marden",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success is not the result of spontaneous combustion. You must set yourself on fire. - Arnold H. Glasow",
    "Success is not to be measured by the position someone has reached in life, but the obstacles he has overcome while trying to succeed. - Booker T. Washington",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
    "Success is the ability to go from failure to failure without losing your enthusiasm. - Winston Churchill",
    "Success is the sum of small efforts repeated day in and day out. - Robert Collier",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Successful people do what unsuccessful people are not willing to do. Dont wish it were easier, wish you were better. - Jim Rohn",
    "The best investment on earth is earth. - Louis Glickman",
    "The best investment you can make is in your own abilities. - Warren Buffett",
    "The best investment you can make is in yourself. - Unknown",
    "The best investment you can make is in yourself. - Warren Buffett",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "The four most dangerous words in investing are: This time its different. - Sir John Templeton",
    "The goal isnt more money, the goal is living life on your own terms. - Chris Brogan",
    "The greatest threat to your financial well-being is your own behavior. - Carl Richards",
    "The habit of managing your money is more important than the amount. - T. Harv Eker",
    "The harder the conflict, the greater the triumph. - George Washington",
    "The individual investor should act consistently as an investor and not as a speculator. - Ben Graham",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "The key to making money is to stay invested. - Suze Orman",
    "The key to success is to focus on goals, not obstacles. - Unknown",
    "The key to success is to start before you are ready. - Marie Forleo",
    "The longer you wait to buy, the more youll pay. - Carrie Wilkerson",
    "The money you save is the slave you have. - Unknown",
    "The more you learn, the more you earn. - Warren Buffett",
    "The most important quality for an investor is temperament, not intellect. - Warren Buffett",
    "The most important thing to do if you find yourself in a hole is to stop digging. - Warren Buffett",
    "The only difference between a rich person and a poor person is how they use their time. - Robert Kiyosaki",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "The secret of success in life is to eat what you like and let the food fight it out inside. - Mark Twain",
    "The secret of success is consistency of purpose. - Benjamin Disraeli",
    "The secret of success is learning how to use pain and pleasure instead of having pain and pleasure use you. If you do that, youre in control of your life. If you dont, life controls you. - Tony Robbins",
    "The secret of success is to know something nobody else knows. - Aristotle Onassis",
    "The secret to getting ahead is getting started. - Mark Twain",
    "The secret to investing is to figure out the value of something – and then pay a lot less. - Joel Greenblatt",
    "The secret to success is to know something nobody else knows. - Aristotle Onassis",
    "The stock market is a device for transferring money from the impatient to the patient. - Warren Buffett",
    "The stock market is filled with individuals who know the price of everything, but the value of nothing. - Philip Fisher",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "There is a gigantic difference between earning a great deal of money and being rich. - Marlene Dietrich",
    "To get rich, you have to be making money while youre asleep. - David Bailey",
    "Wealth is the ability to fully experience life. - Henry David Thoreau",
    "You can be young without money, but you cant be old without it. - Tennessee Williams",
    "You cant outwit fate by standing on the sidelines placing little side bets about the outcome of life. - Brooks Atkinson",
    "You cant outwork a bad diet, and you cant outearn bad spending habits. - Jen Sincero",
    "You must gain control over your money or the lack of it will forever control you. - Dave Ramsey",
    "Every day is a bank account, and time is our currency. No one is rich, no one is poor, weve got 24 hours each. - Christopher Rice",

]